### ISSUE TITLE
Replicate Laravel's artisan make:auth

### ISSUE THREAD

**Issue by bbloom** [LaSalleSoftware/lsv2-basicfrontend-app#2]
See https://github.com/LaSalleSoftware/lsv2-library-pkg/issues/2

**Comment by LaSalleSoftware** [comment]
Done. 

The Dusk tests are mostly undone. I have significant changes coming anyways. 

Final commit inhttps://github.com/LaSalleSoftware/lsv2-basicfrontend-app/issues/1#issue-377569843 should have been applied to this issue.
